// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0E4tLytJNtoTVw-ZPNozcGUyQUxsG5mA',
    appId: '1:226453813207:web:62eb6f2aaa76f823f4bd92',
    messagingSenderId: '226453813207',
    projectId: 'petpetni-460e8',
    authDomain: 'petpetni-460e8.firebaseapp.com',
    storageBucket: 'petpetni-460e8.appspot.com',
    measurementId: 'G-26NCP53CR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO40NhoqAnCtThU3w6BcFwZfQmaOauPxk',
    appId: '1:226453813207:android:9dd4668806142a9bf4bd92',
    messagingSenderId: '226453813207',
    projectId: 'petpetni-460e8',
    storageBucket: 'petpetni-460e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Oeox-GfdsNHmr7QZnmWGpK6UiY7JM1Y',
    appId: '1:226453813207:ios:52505439ae08d957f4bd92',
    messagingSenderId: '226453813207',
    projectId: 'petpetni-460e8',
    storageBucket: 'petpetni-460e8.appspot.com',
    iosBundleId: 'com.example.petpetni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Oeox-GfdsNHmr7QZnmWGpK6UiY7JM1Y',
    appId: '1:226453813207:ios:59e910b5104b7379f4bd92',
    messagingSenderId: '226453813207',
    projectId: 'petpetni-460e8',
    storageBucket: 'petpetni-460e8.appspot.com',
    iosBundleId: 'com.example.petpetni.RunnerTests',
  );
}
