// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

Future<void> initializeFirebase() async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
}
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqQBU_kvxYQFCYqEXxf0AxAMrdLAybusQ',
    appId: '1:403161181771:web:a7a57a1806c37d7f12e7ce',
    messagingSenderId: '403161181771',
    projectId: 'flutterapp-12648',
    authDomain: 'flutterapp-12648.firebaseapp.com',
    storageBucket: 'flutterapp-12648.appspot.com',
    measurementId: 'G-42Z5QQC6PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnEAZG4R6lmALgU1QRB27DScS4WHORf-o',
    appId: '1:403161181771:android:47ffdbb6fa788ed812e7ce',
    messagingSenderId: '403161181771',
    projectId: 'flutterapp-12648',
    storageBucket: 'flutterapp-12648.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBonIpHGGiKfb8nJPmksbrBDAB_W7-EVVA',
    appId: '1:403161181771:ios:57163b485bebd90012e7ce',
    messagingSenderId: '403161181771',
    projectId: 'flutterapp-12648',
    storageBucket: 'flutterapp-12648.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBonIpHGGiKfb8nJPmksbrBDAB_W7-EVVA',
    appId: '1:403161181771:ios:a3cc2ca407a1084612e7ce',
    messagingSenderId: '403161181771',
    projectId: 'flutterapp-12648',
    storageBucket: 'flutterapp-12648.appspot.com',
    iosBundleId: 'com.example.flutterapp.RunnerTests',
  );
}
